services:
  app:
    build: .
    ports:
     - "3000:3000"
    depends_on:
     - pact-broker
    environment:
      BROKER_URL: http://pact-broker:9292
      BRANCH: main
      TAGS: main
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      PACT_DISABLE_SSL_VERIFICATION: "true"
