services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      BROKER_URL: https://api.guildmaster.otterknight.net/
      BRANCH: main
      TAGS: main
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      PACT_DISABLE_SSL_VERIFICATION: "true"
